# conda.yaml
id: python-conda-001
type: module
name: "Conda Environment Setup"
requires: ["base-python-001"]
content: |
  ## Conda Environment Setup

  ### Environment Configuration
  Create `environment.yml`:
  ```yaml
  name: project-env
  channels:
    - conda-forge
    - defaults
  dependencies:
    - python=3.9
    - pip
  ```

  ### Setup Commands
  ```bash
  # Create environment
  conda env create -f environment.yml
  
  # Activate environment
  conda activate project-env
  ```